include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/Project.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/GitHook.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/GitSubmodule.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Helper.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Version.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Module.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Test.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Dependency.cmake")